apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-deployment
  labels: #A tag on the deployments created
    app: echo-server
spec:
  replicas: {{ default 1 .Values.replicas }}
  selector: 
    matchLabels:
      app: echo-server
  template: 
    metadata:
      labels: 
        app: echo-server
    spec:
      containers:
      - name: echo-server-container
        image: {{default "alex0/echo-server:latest" .Values.image}}
        ports:
        - containerPort: {{ default 80 .Values.port }}
