apiVersion: v1
kind: Service
metadata:
  name: echo-server-service
spec:
  ports:
  - name: main
    port: {{ default 80 .Values.port }}
    protocol: TCP
    targetPort: {{ default 80 .Values.port }}
  selector:
    app: echo-server
